### ISSUE TITLE
Incorrect 86 time

### ISSUE THREAD

**Issue by Griesgott** [ShaidenUNI/Turbo_Super_Solo#3]
The bugged console STM time (43.111) is shown on #86 instead of the PC one (43.018).

**Comment by ShaidenUNI** [comment]
Actually true, didn't know about that. Will fix it once I get the correct thousandths for super gold, silver and bronze.

**Comment by Griesgott** [comment]
I don't know how much effort it would take, but would it be possible to do console and PC mode/version? As almost all times are at least slightly different and won't be patched anytime soon I guess. Or at least show for 86 and 197 some note that they differ a lot.

**Comment by ShaidenUNI** [comment]
It is very easy to implement, but I need a bit more info on if it only STM medal that breaks on consoles. If it also breaks super golds, etc., then the whole thing needs recalculation, and it's a pain in the ass.

**Comment by Griesgott** [comment]
As far as I know only STMs are affected (all with non 0 thousand apart from #31 I think). I'll ask some who know more than me.

**Comment by ShaidenUNI** [comment]
Gyrule just confirmed that they're all calculated based on .xx0 STM time.

**Comment by Griesgott** [comment]
The PC time on 86 is still the console one

**Comment by ShaidenUNI** [comment]
I know, that's why I haven't closed the issue. I guess I can put in manually calculated values for now and double check later.
